export const LANGUAGES = [
  {
    code: "de",
    name: "German",
    nativeName: "Deutsch",
    flag: "🇩🇪",
    speechLang: "de-DE",
    grammarTypes: ["Nomen", "Verb", "Adjektiv", "Adverb", "Ausdruck"],
    formsInstructions: `- If Nomen: "der/die/das Word (plural)" e.g. "der Hund (die Hunde)"\n- If Verb: "3rd person present, past tense, perfect" e.g. "läuft, lief, ist gelaufen"\n- Otherwise: null`,
    explanationLang: "German",
    tagLang: "German",
    ui: {
      tabs: { vocabulary: "Wortschatz", today: "Heute", spotify: "Spotify", analyse: "Analyse" },
      filters: { all: "Alle", nouns: "Nomen", verbs: "Verben", expressions: "Ausdrücke", adjectives: "Adjektive", adverbs: "Adverbien", mastered: "✓ Gelernt" },
      strings: {
        placeholder: "Deutsches Wort oder Ausdruck…",
        addButton: "Hinzufügen",
        yourProgress: "Fortschritt",
        words: "Wörter",
        masteredLabel: "gelernt",
        toLearn: "zu lernen",
        startQuiz: "Quiz starten",
        practised: "geübt",
        correct: "richtig",
        masteredQ: "Gelernt?",
        noWords: "Keine Wörter in dieser Kategorie",
        addFirst: "Erstes Wort hinzufügen",
        allTopics: "Alle Themen",
        pasteYoutube: "YouTube-Link einfügen…",
        analyse: "Analysieren",
        analysing: "Analysiere…",
        addWord: "+ Hinzufügen",
        newVideo: "← Neues Video",
        expressionsFound: "Ausdrücke gefunden",
        spotifyIdle: "Spiel etwas auf Spotify…",
        wotdTitle: "Wort des Tages",
        exampleSentences: "Beispielsätze",
        addToVocab: "+ Zur Vokabelliste",
        alreadyInVocab: "✓ Bereits vorhanden",
        newWord: "Neues Wort",
        captionsHint: "Das Video benötigt Untertitel in der Zielsprache (manuell oder automatisch).",
        textAnalysisTitle: "Textanalyse",
        textAnalysisPlaceholder: "Text einfügen — Wörter aus deiner Vokabelliste werden markiert…",
        textWordsFound: "Wörter aus deiner Vokabelliste gefunden",
        textNoWords: "Keine Wörter aus deiner Vokabelliste gefunden",
        textNewText: "← Neuer Text",
        randomWord: "Zufälliges Wort",
        tryAnother: "Anderes Wort",
        topicLabel: "Themen",
        noTopics: "Noch keine Themen",
        addTopicPlaceholder: "Thema hinzufügen… (z. B. reise)",
        quizProgress: "Lernfortschritt",
        ofCorrect: "von",
        wellMastered: "Gut gemeistert! ✨",
        wotdSectionTitle: "Wort des Tages",
      },
    },
  },
  {
    code: "es",
    name: "Spanish",
    nativeName: "Español",
    flag: "🇪🇸",
    speechLang: "es-ES",
    grammarTypes: ["Sustantivo", "Verbo", "Adjetivo", "Adverbio", "Expresión"],
    formsInstructions: `- If Sustantivo: "el/la Word (plural)" e.g. "el perro (los perros)"\n- If Verbo: "yo, tú, él present tense" e.g. "corro, corres, corre"\n- Otherwise: null`,
    explanationLang: "Spanish",
    tagLang: "Spanish",
    ui: {
      tabs: { vocabulary: "Vocabulario", today: "Hoy", spotify: "Spotify", analyse: "Análisis" },
      filters: { all: "Todo", nouns: "Sustantivos", verbs: "Verbos", expressions: "Expresiones", adjectives: "Adjetivos", adverbs: "Adverbios", mastered: "✓ Dominado" },
      strings: {
        placeholder: "Palabra o expresión en español…",
        addButton: "Agregar",
        yourProgress: "Tu progreso",
        words: "palabras",
        masteredLabel: "dominadas",
        toLearn: "por aprender",
        startQuiz: "Iniciar quiz",
        practised: "practicadas",
        correct: "correcto",
        masteredQ: "¿Dominado?",
        noWords: "No hay palabras en esta categoría",
        addFirst: "Agrega tu primera palabra",
        allTopics: "Todos los temas",
        pasteYoutube: "Pega el enlace de YouTube…",
        analyse: "Analizar",
        analysing: "Analizando…",
        addWord: "+ Agregar",
        newVideo: "← Nuevo video",
        expressionsFound: "expresiones encontradas",
        spotifyIdle: "Reproduce algo en Spotify…",
        wotdTitle: "Palabra del día",
        exampleSentences: "Frases de ejemplo",
        addToVocab: "+ Agregar al vocabulario",
        alreadyInVocab: "✓ Ya en tu vocabulario",
        newWord: "Nueva palabra",
        captionsHint: "El video necesita subtítulos en tu idioma objetivo (manuales o automáticos).",
        textAnalysisTitle: "Análisis de texto",
        textAnalysisPlaceholder: "Pega un texto — se resaltarán las palabras de tu vocabulario…",
        textWordsFound: "palabras de tu vocabulario encontradas",
        textNoWords: "No se encontraron palabras de tu vocabulario",
        textNewText: "← Nuevo texto",
        randomWord: "Palabra aleatoria",
        tryAnother: "Otra palabra",
        topicLabel: "Temas",
        noTopics: "Sin temas aún",
        addTopicPlaceholder: "Añadir tema… (ej. viaje)",
        quizProgress: "Progreso del quiz",
        ofCorrect: "de",
        wellMastered: "¡Muy bien dominado! ✨",
        wotdSectionTitle: "Palabra del día",
      },
    },
  },
  {
    code: "fr",
    name: "French",
    nativeName: "Français",
    flag: "🇫🇷",
    speechLang: "fr-FR",
    grammarTypes: ["Nom", "Verbe", "Adjectif", "Adverbe", "Expression"],
    formsInstructions: `- If Nom: "le/la Word (plural)" e.g. "le chien (les chiens)"\n- If Verbe: "je, tu, il present tense" e.g. "cours, cours, court"\n- Otherwise: null`,
    explanationLang: "French",
    tagLang: "French",
    ui: {
      tabs: { vocabulary: "Vocabulaire", today: "Aujourd'hui", spotify: "Spotify", analyse: "Analyse" },
      filters: { all: "Tout", nouns: "Noms", verbs: "Verbes", expressions: "Expressions", adjectives: "Adjectifs", adverbs: "Adverbes", mastered: "✓ Maîtrisé" },
      strings: {
        placeholder: "Mot ou expression en français…",
        addButton: "Ajouter",
        yourProgress: "Votre progrès",
        words: "mots",
        masteredLabel: "maîtrisés",
        toLearn: "à apprendre",
        startQuiz: "Lancer le quiz",
        practised: "pratiqués",
        correct: "correct",
        masteredQ: "Maîtrisé ?",
        noWords: "Aucun mot dans cette catégorie",
        addFirst: "Ajoutez votre premier mot",
        allTopics: "Tous les thèmes",
        pasteYoutube: "Coller le lien YouTube…",
        analyse: "Analyser",
        analysing: "Analyse…",
        addWord: "+ Ajouter",
        newVideo: "← Nouvelle vidéo",
        expressionsFound: "expressions trouvées",
        spotifyIdle: "Jouez quelque chose sur Spotify…",
        wotdTitle: "Mot du jour",
        exampleSentences: "Phrases d'exemple",
        addToVocab: "+ Ajouter au vocabulaire",
        alreadyInVocab: "✓ Déjà dans votre vocabulaire",
        newWord: "Nouveau mot",
        captionsHint: "La vidéo a besoin de sous-titres dans votre langue cible (manuels ou automatiques).",
        textAnalysisTitle: "Analyse de texte",
        textAnalysisPlaceholder: "Collez un texte — les mots de votre vocabulaire seront surlignés…",
        textWordsFound: "mots de votre vocabulaire trouvés",
        textNoWords: "Aucun mot de votre vocabulaire trouvé",
        textNewText: "← Nouveau texte",
        randomWord: "Mot aléatoire",
        tryAnother: "Autre mot",
        topicLabel: "Thèmes",
        noTopics: "Pas encore de thèmes",
        addTopicPlaceholder: "Ajouter un thème… (ex. voyage)",
        quizProgress: "Progression du quiz",
        ofCorrect: "sur",
        wellMastered: "Très bien maîtrisé ! ✨",
        wotdSectionTitle: "Mot du jour",
      },
    },
  },
  {
    code: "it",
    name: "Italian",
    nativeName: "Italiano",
    flag: "🇮🇹",
    speechLang: "it-IT",
    grammarTypes: ["Sostantivo", "Verbo", "Aggettivo", "Avverbio", "Espressione"],
    formsInstructions: `- If Sostantivo: "il/la Word (plural)" e.g. "il cane (i cani)"\n- If Verbo: "io, tu, lui present tense" e.g. "corro, corri, corre"\n- Otherwise: null`,
    explanationLang: "Italian",
    tagLang: "Italian",
    ui: {
      tabs: { vocabulary: "Vocabolario", today: "Oggi", spotify: "Spotify", analyse: "Analisi" },
      filters: { all: "Tutto", nouns: "Nomi", verbs: "Verbi", expressions: "Espressioni", adjectives: "Aggettivi", adverbs: "Avverbi", mastered: "✓ Imparato" },
      strings: {
        placeholder: "Parola o espressione italiana…",
        addButton: "Aggiungi",
        yourProgress: "Il tuo progresso",
        words: "parole",
        masteredLabel: "imparate",
        toLearn: "da imparare",
        startQuiz: "Inizia quiz",
        practised: "praticate",
        correct: "corrette",
        masteredQ: "Imparato?",
        noWords: "Nessuna parola in questa categoria",
        addFirst: "Aggiungi la prima parola",
        allTopics: "Tutti i temi",
        pasteYoutube: "Incolla link YouTube…",
        analyse: "Analizza",
        analysing: "Analisi…",
        addWord: "+ Aggiungi",
        newVideo: "← Nuovo video",
        expressionsFound: "espressioni trovate",
        spotifyIdle: "Riproduci qualcosa su Spotify…",
        wotdTitle: "Parola del giorno",
        exampleSentences: "Frasi di esempio",
        addToVocab: "+ Aggiungi al vocabolario",
        alreadyInVocab: "✓ Già nel tuo vocabolario",
        newWord: "Nuova parola",
        captionsHint: "Il video necessita di sottotitoli nella lingua target (manuali o automatici).",
        textAnalysisTitle: "Analisi del testo",
        textAnalysisPlaceholder: "Incolla un testo — le parole del tuo vocabolario saranno evidenziate…",
        textWordsFound: "parole del tuo vocabolario trovate",
        textNoWords: "Nessuna parola del tuo vocabolario trovata",
        textNewText: "← Nuovo testo",
        randomWord: "Parola casuale",
        tryAnother: "Un'altra parola",
        topicLabel: "Temi",
        noTopics: "Nessun tema ancora",
        addTopicPlaceholder: "Aggiungi tema… (es. viaggio)",
        quizProgress: "Progressi del quiz",
        ofCorrect: "su",
        wellMastered: "Ottimamente padroneggiato! ✨",
        wotdSectionTitle: "Parola del giorno",
      },
    },
  },
  {
    code: "pt",
    name: "Portuguese",
    nativeName: "Português",
    flag: "🇧🇷",
    speechLang: "pt-BR",
    grammarTypes: ["Substantivo", "Verbo", "Adjetivo", "Advérbio", "Expressão"],
    formsInstructions: `- If Substantivo: "o/a Word (plural)" e.g. "o cão (os cães)"\n- If Verbo: "eu, tu, ele present tense" e.g. "corro, corres, corre"\n- Otherwise: null`,
    explanationLang: "Portuguese",
    tagLang: "Portuguese",
    ui: {
      tabs: { vocabulary: "Vocabulário", today: "Hoje", spotify: "Spotify", analyse: "Análise" },
      filters: { all: "Tudo", nouns: "Substantivos", verbs: "Verbos", expressions: "Expressões", adjectives: "Adjetivos", adverbs: "Advérbios", mastered: "✓ Dominado" },
      strings: {
        placeholder: "Palavra ou expressão em português…",
        addButton: "Adicionar",
        yourProgress: "Seu progresso",
        words: "palavras",
        masteredLabel: "dominadas",
        toLearn: "para aprender",
        startQuiz: "Iniciar quiz",
        practised: "praticadas",
        correct: "corretas",
        masteredQ: "Dominado?",
        noWords: "Nenhuma palavra nesta categoria",
        addFirst: "Adicione sua primeira palavra",
        allTopics: "Todos os temas",
        pasteYoutube: "Cole o link do YouTube…",
        analyse: "Analisar",
        analysing: "Analisando…",
        addWord: "+ Adicionar",
        newVideo: "← Novo vídeo",
        expressionsFound: "expressões encontradas",
        spotifyIdle: "Toque algo no Spotify…",
        wotdTitle: "Palavra do dia",
        exampleSentences: "Frases de exemplo",
        addToVocab: "+ Adicionar ao vocabulário",
        alreadyInVocab: "✓ Já no seu vocabulário",
        newWord: "Nova palavra",
        captionsHint: "O vídeo precisa de legendas no idioma alvo (manuais ou automáticas).",
        textAnalysisTitle: "Análise de texto",
        textAnalysisPlaceholder: "Cole um texto — as palavras do seu vocabulário serão destacadas…",
        textWordsFound: "palavras do seu vocabulário encontradas",
        textNoWords: "Nenhuma palavra do seu vocabulário encontrada",
        textNewText: "← Novo texto",
        randomWord: "Palavra aleatória",
        tryAnother: "Outra palavra",
        topicLabel: "Temas",
        noTopics: "Sem temas ainda",
        addTopicPlaceholder: "Adicionar tema… (ex. viagem)",
        quizProgress: "Progresso do quiz",
        ofCorrect: "de",
        wellMastered: "Muito bem dominado! ✨",
        wotdSectionTitle: "Palavra do dia",
      },
    },
  },
  {
    code: "ja",
    name: "Japanese",
    nativeName: "日本語",
    flag: "🇯🇵",
    speechLang: "ja-JP",
    grammarTypes: ["名詞", "動詞", "形容詞", "副詞", "表現"],
    formsInstructions: `- If 動詞: dictionary form, て-form, ます-form e.g. "食べる, 食べて, 食べます"\n- If 名詞: include reading in parentheses e.g. "食べ物 (たべもの)"\n- Otherwise: null`,
    explanationLang: "Japanese",
    tagLang: "Japanese",
    ui: {
      tabs: { vocabulary: "単語帳", today: "今日", spotify: "Spotify", analyse: "分析" },
      filters: { all: "すべて", nouns: "名詞", verbs: "動詞", expressions: "表現", adjectives: "形容詞", adverbs: "副詞", mastered: "✓ 習得済み" },
      strings: {
        placeholder: "日本語の単語や表現…",
        addButton: "追加",
        yourProgress: "学習進捗",
        words: "単語",
        masteredLabel: "習得済み",
        toLearn: "学習中",
        startQuiz: "クイズ開始",
        practised: "練習済み",
        correct: "正解",
        masteredQ: "習得済み?",
        noWords: "この種類の単語はありません",
        addFirst: "最初の単語を追加",
        allTopics: "すべてのテーマ",
        pasteYoutube: "YouTubeリンクを貼り付け…",
        analyse: "分析",
        analysing: "分析中…",
        addWord: "+ 追加",
        newVideo: "← 別の動画",
        expressionsFound: "個の表現が見つかりました",
        spotifyIdle: "Spotifyで何か再生してください…",
        wotdTitle: "今日の単語",
        exampleSentences: "例文",
        addToVocab: "+ 単語帳に追加",
        alreadyInVocab: "✓ 既に追加済み",
        newWord: "別の単語",
        captionsHint: "動画に対象言語の字幕（手動または自動生成）が必要です。",
        textAnalysisTitle: "テキスト分析",
        textAnalysisPlaceholder: "テキストを貼り付けてください — 単語帳の単語がハイライトされます…",
        textWordsFound: "個の単語帳の単語が見つかりました",
        textNoWords: "単語帳の単語は見つかりませんでした",
        textNewText: "← 別のテキスト",
        randomWord: "ランダムな単語",
        tryAnother: "別の単語",
        topicLabel: "テーマ",
        noTopics: "テーマなし",
        addTopicPlaceholder: "テーマを追加… (例: 旅行)",
        quizProgress: "クイズの進捗",
        ofCorrect: "/",
        wellMastered: "よくできました！ ✨",
        wotdSectionTitle: "今日の単語",
      },
    },
  },
  {
    code: "zh",
    name: "Chinese",
    nativeName: "中文",
    flag: "🇨🇳",
    speechLang: "zh-CN",
    grammarTypes: ["名词", "动词", "形容词", "副词", "表达"],
    formsInstructions: `- Include pinyin in parentheses e.g. "狗 (gǒu)"\n- If 动词: include measure word if applicable\n- Otherwise: null`,
    explanationLang: "Chinese",
    tagLang: "Chinese",
    ui: {
      tabs: { vocabulary: "词汇", today: "今天", spotify: "Spotify", analyse: "分析" },
      filters: { all: "全部", nouns: "名词", verbs: "动词", expressions: "表达", adjectives: "形容词", adverbs: "副词", mastered: "✓ 已掌握" },
      strings: {
        placeholder: "输入中文词汇或表达…",
        addButton: "添加",
        yourProgress: "学习进度",
        words: "词汇",
        masteredLabel: "已掌握",
        toLearn: "待学习",
        startQuiz: "开始测验",
        practised: "已练习",
        correct: "正确",
        masteredQ: "已掌握?",
        noWords: "此类别没有词汇",
        addFirst: "添加第一个词汇",
        allTopics: "所有主题",
        pasteYoutube: "粘贴YouTube链接…",
        analyse: "分析",
        analysing: "分析中…",
        addWord: "+ 添加",
        newVideo: "← 新视频",
        expressionsFound: "个表达已找到",
        spotifyIdle: "在Spotify上播放一些音乐…",
        wotdTitle: "今日词汇",
        exampleSentences: "例句",
        addToVocab: "+ 添加到词汇表",
        alreadyInVocab: "✓ 已在词汇表中",
        newWord: "新词汇",
        captionsHint: "视频需要目标语言的字幕（手动或自动生成）。",
        textAnalysisTitle: "文本分析",
        textAnalysisPlaceholder: "粘贴文本 — 词汇表中的单词将被高亮显示…",
        textWordsFound: "个词汇表中的词语已找到",
        textNoWords: "未找到词汇表中的词语",
        textNewText: "← 新文本",
        randomWord: "随机词汇",
        tryAnother: "另一个词",
        topicLabel: "主题",
        noTopics: "暂无主题",
        addTopicPlaceholder: "添加主题… (如：旅行)",
        quizProgress: "测验进度",
        ofCorrect: "/",
        wellMastered: "掌握得很好！ ✨",
        wotdSectionTitle: "今日词汇",
      },
    },
  },
  {
    code: "ko",
    name: "Korean",
    nativeName: "한국어",
    flag: "🇰🇷",
    speechLang: "ko-KR",
    grammarTypes: ["명사", "동사", "형용사", "부사", "표현"],
    formsInstructions: `- If 동사/형용사: dictionary form and polite present e.g. "먹다, 먹어요"\n- If 명사: include romanization e.g. "개 (gae)"\n- Otherwise: null`,
    explanationLang: "Korean",
    tagLang: "Korean",
    ui: {
      tabs: { vocabulary: "어휘", today: "오늘", spotify: "Spotify", analyse: "분석" },
      filters: { all: "전체", nouns: "명사", verbs: "동사", expressions: "표현", adjectives: "형용사", adverbs: "부사", mastered: "✓ 학습 완료" },
      strings: {
        placeholder: "한국어 단어 또는 표현…",
        addButton: "추가",
        yourProgress: "학습 진도",
        words: "단어",
        masteredLabel: "학습 완료",
        toLearn: "학습 중",
        startQuiz: "퀴즈 시작",
        practised: "연습함",
        correct: "정답",
        masteredQ: "학습 완료?",
        noWords: "이 카테고리에 단어가 없습니다",
        addFirst: "첫 번째 단어를 추가하세요",
        allTopics: "모든 주제",
        pasteYoutube: "YouTube 링크 붙여넣기…",
        analyse: "분석",
        analysing: "분석 중…",
        addWord: "+ 추가",
        newVideo: "← 새 동영상",
        expressionsFound: "개의 표현 발견",
        spotifyIdle: "Spotify에서 음악을 재생하세요…",
        wotdTitle: "오늘의 단어",
        exampleSentences: "예문",
        addToVocab: "+ 어휘에 추가",
        alreadyInVocab: "✓ 이미 추가됨",
        newWord: "새 단어",
        captionsHint: "동영상에 목표 언어의 자막이 필요합니다 (수동 또는 자동 생성).",
        textAnalysisTitle: "텍스트 분석",
        textAnalysisPlaceholder: "텍스트를 붙여넣으세요 — 어휘의 단어가 강조됩니다…",
        textWordsFound: "개의 어휘 단어 발견",
        textNoWords: "어휘에서 단어를 찾지 못했습니다",
        textNewText: "← 새 텍스트",
        randomWord: "랜덤 단어",
        tryAnother: "다른 단어",
        topicLabel: "주제",
        noTopics: "주제 없음",
        addTopicPlaceholder: "주제 추가… (예: 여행)",
        quizProgress: "퀴즈 진도",
        ofCorrect: "/",
        wellMastered: "잘 익혔습니다! ✨",
        wotdSectionTitle: "오늘의 단어",
      },
    },
  },
  {
    code: "nl",
    name: "Dutch",
    nativeName: "Nederlands",
    flag: "🇳🇱",
    speechLang: "nl-NL",
    grammarTypes: ["Zelfstandig naamwoord", "Werkwoord", "Bijvoeglijk naamwoord", "Bijwoord", "Uitdrukking"],
    formsInstructions: `- If Zelfstandig naamwoord: "de/het Word (plural)" e.g. "de hond (de honden)"\n- If Werkwoord: "infinitive, past tense, past participle" e.g. "lopen, liep, gelopen"\n- Otherwise: null`,
    explanationLang: "Dutch",
    tagLang: "Dutch",
    ui: {
      tabs: { vocabulary: "Woordenschat", today: "Vandaag", spotify: "Spotify", analyse: "Analyse" },
      filters: { all: "Alle", nouns: "Naamwoorden", verbs: "Werkwoorden", expressions: "Uitdrukkingen", adjectives: "Bijv. naamw.", adverbs: "Bijwoorden", mastered: "✓ Geleerd" },
      strings: {
        placeholder: "Nederlands woord of uitdrukking…",
        addButton: "Toevoegen",
        yourProgress: "Voortgang",
        words: "woorden",
        masteredLabel: "geleerd",
        toLearn: "te leren",
        startQuiz: "Quiz starten",
        practised: "geoefend",
        correct: "correct",
        masteredQ: "Geleerd?",
        noWords: "Geen woorden in deze categorie",
        addFirst: "Voeg je eerste woord toe",
        allTopics: "Alle onderwerpen",
        pasteYoutube: "YouTube-link plakken…",
        analyse: "Analyseren",
        analysing: "Analyseren…",
        addWord: "+ Toevoegen",
        newVideo: "← Nieuwe video",
        expressionsFound: "uitdrukkingen gevonden",
        spotifyIdle: "Speel iets op Spotify…",
        wotdTitle: "Woord van de dag",
        exampleSentences: "Voorbeeldzinnen",
        addToVocab: "+ Toevoegen aan woordenschat",
        alreadyInVocab: "✓ Al in uw woordenschat",
        newWord: "Nieuw woord",
        captionsHint: "De video heeft ondertitels nodig in de doeltaal (handmatig of automatisch).",
        textAnalysisTitle: "Tekstanalyse",
        textAnalysisPlaceholder: "Plak een tekst — woorden uit uw woordenschat worden gemarkeerd…",
        textWordsFound: "woorden uit uw woordenschat gevonden",
        textNoWords: "Geen woorden uit uw woordenschat gevonden",
        textNewText: "← Nieuwe tekst",
        randomWord: "Willekeurig woord",
        tryAnother: "Ander woord",
        topicLabel: "Onderwerpen",
        noTopics: "Nog geen onderwerpen",
        addTopicPlaceholder: "Onderwerp toevoegen… (bijv. reizen)",
        quizProgress: "Quizvoortgang",
        ofCorrect: "van",
        wellMastered: "Goed beheerst! ✨",
        wotdSectionTitle: "Woord van de dag",
      },
    },
  },
  {
    code: "tr",
    name: "Turkish",
    nativeName: "Türkçe",
    flag: "🇹🇷",
    speechLang: "tr-TR",
    grammarTypes: ["İsim", "Fiil", "Sıfat", "Zarf", "İfade"],
    formsInstructions: `- If Fiil: infinitive and present tense e.g. "koşmak, koşuyor"\n- Otherwise: null`,
    explanationLang: "Turkish",
    tagLang: "Turkish",
    ui: {
      tabs: { vocabulary: "Kelimeler", today: "Bugün", spotify: "Spotify", analyse: "Analiz" },
      filters: { all: "Tümü", nouns: "İsimler", verbs: "Fiiller", expressions: "İfadeler", adjectives: "Sıfatlar", adverbs: "Zarflar", mastered: "✓ Öğrenildi" },
      strings: {
        placeholder: "Türkçe kelime veya ifade…",
        addButton: "Ekle",
        yourProgress: "İlerleme",
        words: "kelime",
        masteredLabel: "öğrenildi",
        toLearn: "öğrenilecek",
        startQuiz: "Quiz başlat",
        practised: "alıştırıldı",
        correct: "doğru",
        masteredQ: "Öğrenildi?",
        noWords: "Bu kategoride kelime yok",
        addFirst: "İlk kelimeyi ekle",
        allTopics: "Tüm konular",
        pasteYoutube: "YouTube bağlantısını yapıştır…",
        analyse: "Analiz et",
        analysing: "Analiz ediliyor…",
        addWord: "+ Ekle",
        newVideo: "← Yeni video",
        expressionsFound: "ifade bulundu",
        spotifyIdle: "Spotify'da bir şeyler çal…",
        wotdTitle: "Günün kelimesi",
        exampleSentences: "Örnek cümleler",
        addToVocab: "+ Kelime listesine ekle",
        alreadyInVocab: "✓ Zaten listenizde",
        newWord: "Yeni kelime",
        captionsHint: "Videonun hedef dilde altyazısı olması gerekiyor (manuel veya otomatik).",
        textAnalysisTitle: "Metin analizi",
        textAnalysisPlaceholder: "Bir metin yapıştırın — kelime listenizdeki kelimeler vurgulanacak…",
        textWordsFound: "kelime listenizdeki kelime bulundu",
        textNoWords: "Kelime listenizdeki hiçbir kelime bulunamadı",
        textNewText: "← Yeni metin",
        randomWord: "Rastgele kelime",
        tryAnother: "Başka kelime",
        topicLabel: "Konular",
        noTopics: "Henüz konu yok",
        addTopicPlaceholder: "Konu ekle… (örn. seyahat)",
        quizProgress: "Quiz ilerlemesi",
        ofCorrect: "/",
        wellMastered: "Çok iyi öğrenildi! ✨",
        wotdSectionTitle: "Günün kelimesi",
      },
    },
  },
  {
    code: "id",
    name: "Indonesian",
    nativeName: "Bahasa Indonesia",
    flag: "🇮🇩",
    speechLang: "id-ID",
    grammarTypes: ["Kata Benda", "Kata Kerja", "Kata Sifat", "Kata Keterangan", "Ungkapan"],
    formsInstructions: `- If Kata Kerja: base form and me- prefix form e.g. "makan, memakan"\n- If Kata Benda: include plural reduplication if common e.g. "buku (buku-buku)"\n- Otherwise: null`,
    explanationLang: "Indonesian",
    tagLang: "Indonesian",
    ui: {
      tabs: { vocabulary: "Kosakata", today: "Hari Ini", spotify: "Spotify", analyse: "Analisis" },
      filters: { all: "Semua", nouns: "Kata Benda", verbs: "Kata Kerja", expressions: "Ungkapan", adjectives: "Kata Sifat", adverbs: "Kata Keterangan", mastered: "✓ Dikuasai" },
      strings: {
        placeholder: "Kata atau ungkapan dalam bahasa Indonesia…",
        addButton: "Tambah",
        yourProgress: "Kemajuan Anda",
        words: "kata",
        masteredLabel: "dikuasai",
        toLearn: "untuk dipelajari",
        startQuiz: "Mulai kuis",
        practised: "dipraktikkan",
        correct: "benar",
        masteredQ: "Dikuasai?",
        noWords: "Tidak ada kata dalam kategori ini",
        addFirst: "Tambah kata pertama Anda",
        allTopics: "Semua topik",
        pasteYoutube: "Tempel tautan YouTube…",
        analyse: "Analisis",
        analysing: "Menganalisis…",
        addWord: "+ Tambah",
        newVideo: "← Video baru",
        expressionsFound: "ungkapan ditemukan",
        spotifyIdle: "Putar sesuatu di Spotify…",
        wotdTitle: "Kata Hari Ini",
        exampleSentences: "Kalimat contoh",
        addToVocab: "+ Tambah ke kosakata",
        alreadyInVocab: "✓ Sudah ada di kosakata",
        newWord: "Kata baru",
        captionsHint: "Video membutuhkan teks dalam bahasa target (manual atau otomatis).",
        textAnalysisTitle: "Analisis teks",
        textAnalysisPlaceholder: "Tempel teks — kata-kata dari kosakata Anda akan disorot…",
        textWordsFound: "kata dari kosakata Anda ditemukan",
        textNoWords: "Tidak ada kata dari kosakata Anda yang ditemukan",
        textNewText: "← Teks baru",
        randomWord: "Kata acak",
        tryAnother: "Kata lain",
        topicLabel: "Topik",
        noTopics: "Belum ada topik",
        addTopicPlaceholder: "Tambah topik… (mis. perjalanan)",
        quizProgress: "Progres kuis",
        ofCorrect: "dari",
        wellMastered: "Sudah dikuasai dengan baik! ✨",
        wotdSectionTitle: "Kata Hari Ini",
      },
    },
  },
];

export function getLanguage(code) {
  return LANGUAGES.find((l) => l.code === code) || LANGUAGES[0];
}
